baseurl = "/"
title = "the web"
author = "GH"
canonifyurls = true
paginate = 3
theme = "aether"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[main.menu]]
name = "Rbook"
url = "/rbook/"

[params]
brand = "aether"
description = "aether Hugo theme for blogs"
bgimg = "img/ignasi_pattern_s.png"
